import canonicalLaneMathlib.AdmissibleClass
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.LoopGroup
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.CentralExtension
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.Cocycle
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.Representation

namespace HautevilleHouse
namespace LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean

def ConstrainedLoopGroupsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_loop_groups_endgame (A : AdmissibleClass) :
    ConstrainedLoopGroupsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean
end HautevilleHouse