import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.LoopGroupDefinitions
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.CentralExtension
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.LoopGroupRepresentations
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.AffineLieAlgebra
import LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean

-- This module aggregates all domain-specific files.

end LoopGroupsConstructionsGroupTheoreticTheoremCanonicalLaneLean
end HautevilleHouse